// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Map, MapTableId } from "./tables/Map.sol";
import { Cities, CitiesData, CitiesTableId } from "./tables/Cities.sol";
import { Soldiers, SoldiersData, SoldiersTableId } from "./tables/Soldiers.sol";
