// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameSystem {
  function pseudoConstructor() external;

  function buyCity(uint256 cityId) external payable;

  function setCityOwner(address newOwner, uint256 cityId) external;

  function setSector(uint256 cityId, uint256 sectorNumber, uint256 buildingType) external;

  function createSoldier(
    uint256 soldierId,
    address allegiance,
    uint256 tileId,
    uint256 attack,
    uint256 defense,
    uint256 mobility
  ) external;

  function checkAdjacent(int256[3] memory tileA, int256[3] memory tileB) external pure returns (bool);

  function moveSoldier(uint256 soldierId, uint256 destinationTileId) external returns (bool);

  function soldierAttack(uint256 attackingSoldierId, uint256 defendingSoldierId) external returns (bool);

  function checkTerritoryClaim(uint256 soldierId) external returns (bool);
}
